// <auto-generated />
namespace AST1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class providerError : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(providerError));
        
        string IMigrationMetadata.Id
        {
            get { return "202308222036160_providerError"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
